version: '3.8'
services:
  simple-blog:
    container_name: simple-blog
    image: php:7.2-apache
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
  db:
    container_name: db
    image: mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: change-me
      MYSQL_DATABASE: default
    ports:
      - "3306:3306"
